### PR TITLE
Fix dry-configurable deprecation warnings

### LINKED ISSUE #97: Dry configurable update
### Issue with Dry Configurable

In ruby 3.1 there is this error:
`[dry-configurable] default value as positional argument to settings is deprecated and will be removed in the next major version
Provide a `default:` keyword argument instead`

These warnings are probably present because the version of dry-configurable gem that is used, has seen plenty of updates. Possibly an update would fix it.

Not a major issue for the time being, but it polutes the log with many warnings. After the deprecation though, it will render it unusable.

### Environment

 - Library version: ruby 3.1.2
 - Language/framework version: Rails 7
 - OS version: macOS 12.4

### PR DESCRIPTION
**Pull request by dalizard**
## Description
With version [0.13.0](https://github.com/dry-rb/dry-configurable/blob/main/CHANGELOG.md#changed-2) of the [dry-configurable](https://github.com/dry-rb/dry-configurable) gem, the default value for a setting provided as a positional argument is deprecated. The `default:` keyword argument should be used instead.

This pull request fixes #97.

## Checklist

- [ ] Tests (if applicable)
- [ ] Documentation (if applicable)
- [ ] Changelog stub (or use [conventional commit messages](https://www.conventionalcommits.org/))

### CODE REVIEW

**Comment by skliask** [comment]
Nice man!

I was about to work on this too. Good job! 🦾

**Comment by dmitry-mukhin** [comment]
<3

File: lib/uploadcare.rb [hunk 1]
```diff
@@ -32,18 +32,18 @@
...
+  setting :rest_api_root,             default: 'https://api.uploadcare.com'
+  setting :upload_api_root,           default: 'https://upload.uploadcare.com'
+  setting :max_request_tries,         default: 100
+  setting :base_request_sleep,        default: 1 # seconds
+  setting :max_request_sleep,         default: 60.0 # seconds
+  setting :sign_uploads,              default: false
+  setting :upload_signature_lifetime, default: 30 * 60 # seconds
+  setting :max_throttle_attempts,     default: 5
+  setting :upload_threads,            default: 2 # used for multiupload only ATM
+  setting :framework_data,            default: ''
```
Comment (dmitry-mukhin) [inline lib/uploadcare.rb:48]: can you tell me if this (formatting) is conventional ruby?

**Comment by dmitry-mukhin** [comment]
@rsedykh we need to figure out if we want to drop support for rubies <= 2.7

**Comment by dalizard** [comment]
@dmitry-mukhin Hmm, it's interesting that the <= 2.7 specs are failing -- I don't see how this is related to my changes 🤔

**Comment by dmitry-mukhin** [comment]
@dalizard I assume it's due to `dry-configurable` reqs

**Comment by dalizard** [comment]
@dmitry-mukhin You are spot on! The dry-configurable gem has introduced the `default` keyword argument and deprecated the positional default argument in version 0.13.0, which also requires Ruby >= 2.6.0. In essence there is no way to use the `default` keyword argument if Ruby is < 2.6.0. There are different ways to approach and solve this -- [my idea](https://github.com/uploadcare/uploadcare-ruby/pull/98/commits/07cd09d59c53df2326406916828562d287adf1c6) is to maintain Ruby backwards compatibility but also not simply silence warning messages.

**Comment by mykhi** [comment]
Bumping to get it merged.
